### PR TITLE
Assign

### PR DESCRIPTION
**Pull request by JohnCoene**
Hi Colin,

This PR attempts at implementing `assign` method to create JSON arrays from R. 

```r
n <- NodeSession$new()
n$assign(carz, cars[1:10, ])
#> undefined
n$get(carz)
#> [[1]]
#>    speed dist
#> 1      4    2
#> 2      4   10
#> 3      7    4
#> 4      7   22
#> 5      8   16
#> 6      9   10
#> 7     10   18
#> 8     10   26
#> 9     10   34
#> 10    11   17
```

This is obviously inspired by V8 and implies one minor change. 

The data is serialized to JSON then collapsed into a string and parsed in JSON with `JSON.parse`. This means it must be read back in R with `JSON.stringify`, otherwise bare `get` method fails as jsonlite cannot convert the object (invalid JSON).

Therefore the `get` method uses `lapply` to loop over the input variables (`...`) if jsonlite fails then it assumes it is a JSON object and fetches appropriately: _this means that `get` returns a `list`_ (output of `lapply`).
 
Personally, I would say it should emulate the V8 package and have `get` return only a single variable, getting rid of the three-dots construct. This would get rid of return-list-issue and is, I would argue, clearer to the user. I'm unsure when I would really need to fetch multiple individual objects as a single vector, but I might be wring here.

Moreover to follow your convention I also allow passing bare names like you do in the `get` method but I'm unsure this is the right place for tidyeval. Again, I would do like V8 (below) but I'm no expert on the topic.

```r
n <- NodeSession$new()
n$assign("car*, cars[1:10, ])
n$get("car")
```

Let me know what you think, I've tried my best to document what is being done but wouldn't be surprised it's not clear.

### CODE REVIEW

**Comment by JohnCoene** [comment]
I realise I made a typo in that last snippet of code(~this should be~`*`), it's of course meant to be:

```r
n <- NodeSession$new()
n$assign("car", cars[1:10, ])
n$get("car")
```

**Comment by JohnCoene** [comment]
Riddle me this :confused: ...

Je comprends plus rien, tout fonctionne nickel sur Mac OS, je passe sur Ubuntu 18 et je rencontre une erreur que je coomprends pas trop; j'ai rajouté une autre erreur au cas ou mais ca deviens moche `Cannot parse results.`.

```r
n <- NodeSession$new()
n$assign(vehicles, cars[1:5, ]) 
n$get(vehicles)
#> Error: Cannot parse results.
```

J'ai cette erreur dans un autre de mes package qui utilise {subpress}, peut-être as-tu une solution.

**Comment by JohnCoene** [comment]
Alright...

Tu peu ignoré le commentaire précédent. Un petit "hack," peut-être pas très élégant mais qui fonctionne, `while(inherits(results, "error"))`, ca tente deux fois ce qui "fix" le problème.

**Comment by JohnCoene** [comment]
I went with restraining the `get` method to a single variable, it's too confusing to return a list (see previous comments).

**Comment by JohnCoene** [comment]
So to expand/clarify previous comment. This PR now means that one can only get a single variable at a time.

```r
library(bubble)

n <- NodeSession$new()
n$assign(vehicles, cars[1:5, ])                                                                           
n$get(vehicles)                                                                                           
#>  speed dist
#>1     4    2
#>2     4   10
#>3     7    4
#>4     7   22
#>5     8   16
```

But then, the code below fails where it would previously work.

```r
n$eval("x = 1;")
n$get(x, vehicles)                                                                                        
#> Error in n$get(x, vehicles) : unused argument (vehicles)
```

From my tests so far the `assign` method works well.

**Comment by JohnCoene** [comment]
Doing some more thinking on this. Currently `assign` essentially converts the input to JSON and pastes that as a character vector of length 1 which is then parsed in node with `JSON.parse`.

For larger datasets one should probably use the `fs` package. I was wondering what you thought of the following.

1. check if `fs` module can be imported.
2. if no, use currently implemented method.
3. if yes, use a tempfile; write results to temp json, read and parse in node, unlink temp file.

**Comment by JohnCoene** [comment]
I thought it was an interesting exercise so I went ahead and implemented it; it's actually the only way I know to see whether and how something could work.

So. now on initialisation, a node function called `isModuleAvalailableToBubble` is declared. It's named that way to make ensure it will not eventually be overridden by the user. This function is paired with an R function called `check_module_avail` which takes the name of a module and returns a boolean: `TRUE` if the module can be imported.

I thus had to add a private field called `fs_imported` which defaults to `FALSE` and is set to `TRUE` if the module has been imported. This is to ensure we don't define and re-define `fs = require('fs')`.

So when one `assign`s an object the method checks whether `fs` is available, if it is it imports it (once!) then creates a temp JSON file where the object is serialized to. This is then read in node and unlinked once done.

The befits seem apparent to me.

```r
library(dplyr)

# create a large tibble
df <- tibble(x = 1:2, y = c("a", "b")) %>% slice(rep(1:n(), each = 100000))

dim(df)                                                                                
#> [1] 200000      2

n <- NodeSession$new()
n$assign(mydata, df)
```

The above is surprisingly fast! The bottleneck is fetching the data back, which leads me to think we should probably do the same the other way around: write a tempfile from node then read JSON from there in R.

```r
# that'll take a while
n$get(mydata)
```

This all can be undone but I think it could be a nice feature otherwise importing thousands of rows as a flattened JSON string might take some time. Though then again, it's perhaps not ideal. Let me know what you think @ColinFay

**Review by ColinFay — COMMENTED** [review]
Thanks 🙏 

That's a dope feature 💪

**Pull request merged**
