### PR TITLE
npm

### PR DESCRIPTION
**Pull request by JohnCoene**
Hi Colin,

{bubble} looks awesome and has tremendous potential. I thought of adding support for npm so that we can easily install and import packages, e.g.: the express app example in the README does not work unless one has globally installed it previously.

I added the still very simple `NpmSession` R6 to install.

```r
library(bubble)

npm <- NpmSession$
  new()$
  install("express")
```

Note that then `npm$install()` is similar to `npm install` which makes it great to share work of course.

Then the example works.

```r
n <- NodeSession$new()

n$eval("const express = require('express');")
#> undefined
n$eval("app = express()", print = FALSE)

n$eval("app.get('/', function (req, res) {", print = FALSE)
n$eval("  res.send('Hello R!')")
n$eval("})", print = FALSE)
n$eval("app.listen(3002)", print = FALSE)

x <- httr::GET("http://127.0.0.1:3002") 
httr::content(x)

n$kill()

httr::GET("http://127.0.0.1:3002")
```

My tests did work fine but it probably needs some more.

### CODE REVIEW

**Comment by ColinFay** [comment]
Thanks @JohnCoene! 

That definitely makes sense to have a mechanism to control `npm`, cheers!

Here are a few feedbacks: 

- I don't feel like we should call this `NpmSession` as we are not really opening an interactive session in which we can write (it's more of a series of "one time calls", how about simply `Npm` ? 

- I think we could add a method that can call any `npm` command from: 

```
colin:bubble colin$ npm

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci,
    cit, clean-install, clean-install-test,
    completion, config, create, ddp, dedupe,
    deprecate, dist-tag, docs, doctor, edit, explore,
    get, help, help-search, hook, i, init, install,
    install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack,
    ping, prefix, profile, prune, publish, rb,
    rebuild, repo, restart, root, run, run-script, s,
    se, search, set, shrinkwrap, star, stars, start,
    stop, t, team, test, token, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view,
    whoami
```
So maybe something like 

```r
  cmd = function(command, args = NULL){
    #browser()
    res <- processx::run(
      command = self$bin,
      args = c(command, args),
      echo = FALSE
    )
    if (res$status == 0){
      cat(res$stdout)
    }
  }
```

Which could lead to: 

```r
> pkgload::load_all()
Loading bubble
> x <- Npm$new()
> x$cmd("ls")
bubble@1.0.0 /Users/colin/Seafile/documents_colin/R/opensource/bubble
└── (empty)

> x$cmd("search", "bubble") 
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
bubble                    | Domains for the…     | =nicola =pgte   | 2012-03-21 | 0.1.0    |         
clinic                    | Clinic.js diagnoses… | =admataz…       | 2019-10-31 | 5.0.0    | performance tool analysis clinic bubbleprof doctor flamegraph flame bubble
@nearform/bubbleprof      | Programmable…        | =admataz…       | 2019-11-07 | 3.0.1    | 
bubble-stream-error       | Bubble errors from…  | =alessioalex    | 2015-11-26 | 1.0.0    | bubble error stream stream-error bubble-stream-error
style-bubble              | style components in… | =ddunc          | 2019-03-17 | 1.0.5    | react styled-components css unset
bubblesub                 | Observables based…   | =zenwork        | 2019-11-03 | 1.3.0    | typescript DI publisher subscriber event
react-simple-tooltip      | A lightweight and…   | =xuopled        | 2019-07-25 | 2.6.1    | react tooltip bubble
@weknow/react-bubble-char | ReactJS component…   | =enzolutions…   | 2019-05-13 | 1.0.12   | ReactJS Component D3 Charts Bubble Graphics
t-d3                      |                      |                 |            |          |                                            
bubble-validator          | A multiple…          | =ruphilau       | 2019-03-01 | 1.2.5    | 
bubble-hearts             | (<3kb) 💖Bubble…     | =lixinliang     | 2017-05-15 | 1.0.0    | bubble canvas animation hearts like fly live
algo-sort-bubble          | Bubble sort…         | =bredele        | 2017-04-09 | 1.1.0    | sort algorithm bubble
vue-sticky-bubble         | A floating menu…     | =sahajr         | 2018-01-15 | 0.2.3    | 
node-bubsort              | node bubble sort…    | =eepetore       | 2019-10-13 | 0.0.4    | bubble sort algorithm node
js-sorting-algo           | Sorting Algorithms…  | =kumar_gaurav_… | 2019-10-16 | 1.0.1    | DataStruture sorting algorithms js-sorting-algorithms js sorting quickSort bubbleSort mergeSort radixSort insertionSort
@jasonheecs/js-sorting    | A list of common…    | =jasonheecs     | 2018-05-02 | 1.0.2    | sorting algorithms sort bubble sort insertion sort merge sort quicksort selection sort
@domoinc/person-bubble    | PersonBubble - Domo… | =jonathon.meng… | 2016-04-06 | 3.0.2    | domo app
ljz                       | javascript sort…     | =yt_fan         | 2017-04-27 | 1.0.5    | js bubble insert quick sort
react-nice-bubble         | A customizable…      | =vipcxj         | 2019-09-22 | 1.1.1    | bubble react transparent border radius
image-charts              | The ImageCharts…     | =jwerre         | 2019-06-19 | 0.0.9    | chart charts image imagecharts png jpg jpeg gif animated api pie bar horizontal-bar bubble doughnut line polar
sorting-algorithms        | Collection of…       | =luongnv89      | 2018-11-13 | 1.1.0    | algorithms sorting merge sort quick sort bubble selection insertion sort
```

That still makes sense to have an alias for install as it might be the most common thing we use. 

- I'm not sure about using `{usethis}` there. I'd rather not have it as a dependency for just one function 🤔. We could either rewrite it or simply print a message to the console to remind the user to add this to the `ignore` files in the project.

- Can you add yourself as a `ctb`? :)

Are you willing to continue to work on that? No problem if no, I'll take over what you've started :) 

Anyhow, thanks a lot for your contribution!!

**Comment by JohnCoene** [comment]
Hi Colin,

Thanks for the feedback! Would love to contribute more to the project if I can, I love both node and R, bringing them together would be grand!

- [x] You're right, `NpmSession` did not make much sense so I renamed it to `Npm`.
- [x] There is indeed no real need for `usethis` so I removed the dependency. Instead a perhaps too colourful message is printed suggesting the user should add `node_modules` to `.gitignore`.
- [ ] I did _not_ add a message suggesting to add files to `.Rbuildignore` thinking 1) it would be too many messages printed on the console and 2) it package devs and maintainers probably know about this.
- [x] I did some better abstraction on the `Npm` class (there was some horrid code in there :smiley: )
- [ ] In the spirit of limiting dependencies I did not use `processx` and simply used `system2` which seems to do the job just fine but that can of course be changed if there are advantages to the latter that I miss.
- [x] Added the `cmd` method that was a good idea indeed.
- [x] If there is a convenience method for `install` there might as well be one for `uninstall`.

:warning: I took the liberty of documenting the package using `roxygen2` version `7.0.0` since it supports R6, please check that the documentation for `NodeSession` is correct.

```r
library(bubble)

npm <- Npm$
  new()$
  install("express")

# list express & deps
npm$cmd("ls")
 [1] "bubble@1.0.0 /home/jp/Packages/bubble" 
 [2] "└─┬ express@4.17.1"                    
 [3] "  ├─┬ accepts@1.3.7"                   
 [4] "  │ ├─┬ mime-types@2.1.25"             
 [5] "  │ │ └── mime-db@1.42.0"              
 [6] "  │ └── negotiator@0.6.2"              
 [7] "  ├── array-flatten@1.1.1"             
 [8] "  ├─┬ body-parser@1.19.0"              
 [9] "  │ ├── bytes@3.1.0"                   
[10] "  │ ├── content-type@1.0.4 deduped"    
[11] "  │ ├── debug@2.6.9 deduped"           
[12] "  │ ├── depd@1.1.2 deduped"            
[13] "  │ ├─┬ http-errors@1.7.2"             
[14] "  │ │ ├── depd@1.1.2 deduped"          
[15] "  │ │ ├── inherits@2.0.3"              
[16] "  │ │ ├── setprototypeof@1.1.1 deduped"
[17] "  │ │ ├── statuses@1.5.0 deduped"      
[18] "  │ │ └── toidentifier@1.0.0"          
[19] "  │ ├─┬ iconv-lite@0.4.24"             
[20] "  │ │ └── safer-buffer@2.1.2"          
[21] "  │ ├── on-finished@2.3.0 deduped"     
[22] "  │ ├── qs@6.7.0 deduped"              
[23] "  │ ├─┬ raw-body@2.4.0"                
[24] "  │ │ ├── bytes@3.1.0 deduped"         
[25] "  │ │ ├── http-errors@1.7.2 deduped"   
[26] "  │ │ ├── iconv-lite@0.4.24 deduped"   
[27] "  │ │ └── unpipe@1.0.0 deduped"        
[28] "  │ └── type-is@1.6.18 deduped"        
[29] "  ├─┬ content-disposition@0.5.3"       
[30] "  │ └── safe-buffer@5.1.2 deduped"     
[31] "  ├── content-type@1.0.4"              
[32] "  ├── cookie@0.4.0"                    
[33] "  ├── cookie-signature@1.0.6"          
[34] "  ├─┬ debug@2.6.9"                     
[35] "  │ └── ms@2.0.0"                      
[36] "  ├── depd@1.1.2"                      
[37] "  ├── encodeurl@1.0.2"                 
[38] "  ├── escape-html@1.0.3"               
[39] "  ├── etag@1.8.1"                      
[40] "  ├─┬ finalhandler@1.1.2"              
[41] "  │ ├── debug@2.6.9 deduped"           
[42] "  │ ├── encodeurl@1.0.2 deduped"       
[43] "  │ ├── escape-html@1.0.3 deduped"     
[44] "  │ ├── on-finished@2.3.0 deduped"     
[45] "  │ ├── parseurl@1.3.3 deduped"        
[46] "  │ ├── statuses@1.5.0 deduped"        
[47] "  │ └── unpipe@1.0.0"                  
[48] "  ├── fresh@0.5.2"                     
[49] "  ├── merge-descriptors@1.0.1"         
[50] "  ├── methods@1.1.2"                   
[51] "  ├─┬ on-finished@2.3.0"               
[52] "  │ └── ee-first@1.1.1"                
[53] "  ├── parseurl@1.3.3"                  
[54] "  ├── path-to-regexp@0.1.7"            
[55] "  ├─┬ proxy-addr@2.0.5"                
[56] "  │ ├── forwarded@0.1.2"               
[57] "  │ └── ipaddr.js@1.9.0"               
[58] "  ├── qs@6.7.0"                        
[59] "  ├── range-parser@1.2.1"              
[60] "  ├── safe-buffer@5.1.2"               
[61] "  ├─┬ send@0.17.1"                     
[62] "  │ ├── debug@2.6.9 deduped"           
[63] "  │ ├── depd@1.1.2 deduped"            
[64] "  │ ├── destroy@1.0.4"                 
[65] "  │ ├── encodeurl@1.0.2 deduped"       
[66] "  │ ├── escape-html@1.0.3 deduped"     
[67] "  │ ├── etag@1.8.1 deduped"            
[68] "  │ ├── fresh@0.5.2 deduped"           
[69] "  │ ├── http-errors@1.7.2 deduped"     
[70] "  │ ├── mime@1.6.0"                    
[71] "  │ ├── ms@2.1.1"                      
[72] "  │ ├── on-finished@2.3.0 deduped"     
[73] "  │ ├── range-parser@1.2.1 deduped"    
[74] "  │ └── statuses@1.5.0 deduped"        
[75] "  ├─┬ serve-static@1.14.1"             
[76] "  │ ├── encodeurl@1.0.2 deduped"       
[77] "  │ ├── escape-html@1.0.3 deduped"     
[78] "  │ ├── parseurl@1.3.3 deduped"        
[79] "  │ └── send@0.17.1 deduped"           
[80] "  ├── setprototypeof@1.1.1"            
[81] "  ├── statuses@1.5.0"                  
[82] "  ├─┬ type-is@1.6.18"                  
[83] "  │ ├── media-typer@0.3.0"             
[84] "  │ └── mime-types@2.1.25 deduped"     
[85] "  ├── utils-merge@1.0.1"               
[86] "  └── vary@1.1.2"                      
[87] "" 

npm$uninstall("express")

# no modules
npm$cmd("ls")
[1] "bubble@1.0.0 /home/jp/Packages/bubble"
[2] "└── (empty)"                          
[3] ""
```

Thanks again, any more feedback is of course welcome :)

**Comment by JohnCoene** [comment]
It did occur to me last night (I have wonderful dreams!) that perhaps a convenient `install_npm_pkg` function could be useful since I would assume this is the core functionality of npm. Personally I mostly use that, having to `Npm$new()$install("express")`to install every module might be tedious.

What do you think?

**Comment by ColinFay** [comment]
That's awesome, thanks !!

**Comment by ColinFay** [comment]
I'm opening an issue to track `npm_install()` : https://github.com/ColinFay/bubble/issues/4

**Pull request merged**
